### ISSUE TITLE
Feature request:  URL field be able to save multiple online URL's

### ISSUE THREAD

**Issue by hitam4450** [mrzapp/nextcloud-cookbook#152]
hello, 

I love the Cookbook app which is a great tool for me to organize my recipes from all over the world.
However, these days may recipes could be found online by text or video.

How about to make the URL field be able to save multiple online URLs for reference ??

regards, hitam4450

**Comment by mrzapp** [comment]
This sounds like a huge time saver if you have a lot of recipes. I'll put it in the 0.7.0 milestone for now.

I imagine that instead of just the one input field, we will create a modal window where multiple URLs can be accessed. Each recipe would attempt import sequentially, and if some imports fail, the rest will continue, but the failed ones will be highlighted.

**Comment by mrzapp** [comment]
A more descriptive issue #288 has been submitted, so closing this one
