### ISSUE TITLE
Cant reach recipe sites

### ISSUE THREAD

**Issue by TomG736** [mrzapp/nextcloud-cookbook#156]
I have version 0.5.7 running on my nextcloud which is running in docker ( running nextcloud:latest from dockerhub, 18.0.1)

Whenever I try and add a recipie I get the following errors:

Popup error:
Could not add recipe: "Could not fetch site https:\/\/www.deliaonline.com\/recipes\/main-ingredient\/eggs-recipes\/basic-pancakes"

Error from log:
```json
{"reqId":"jdqf7L06eSbJSY4rGotl","level":3,"time":"2020-03-10T22:06:53+00:00","remoteAddr":"0000:0000:0000:0000:0000:0000:0000:0000","user":"USER","app":"PHP","method":"POST","url":"/apps/cookbook/add","message":"file_get_contents(https://www.deliaonline.com/recipes/main-ingredient/eggs-recipes/basic-pancakes): failed to open stream: Connection timed out at /var/www/html/custom_apps/cookbook/lib/Service/RecipeService.php#579","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.87 Safari/537.36","version":"18.0.1.3","id":"5e680f7d66a89"}
```

I have tried running curl with the target url from inside docker container and it works so the docker containers networking doesnt seem to be an issue.

Do you have any idea whats going wrong/what I need to change?

**Comment by mrzapp** [comment]
If it's getting timeout issues, I have no clue what that might be, since we don't impose any sort of throttling, we just use basic PHP HTTP requests. 

On the latest unstable code from 0.6.0, I am able to pull the recipe, but not the image, since schema.org is not implemented properly on that site.

I'm sorry I can't give you a better answer, but your particular problem seems to be outside the scope of this app
