### ISSUE TITLE
Cooking Time, Total time and Preparation time are reset to 00:00

### ISSUE THREAD

**Issue by Schlaubischlump** [mrzapp/nextcloud-cookbook#164]
Upgrading from v0.5.7 to v0.6 resets the time values. The json dictionary does contain the original information e.g. `"cookTime_test": 'P0Y0M0DT0H15M0S'`, but with a `_test` suffix. The actual displayed values are stored in `"cookTime": PT0H0M` without the suffix and are reset to `PT0H0M` after the upgrade. Is this expected behaviour / a known issue ?

**Comment by mrzapp** [comment]
@Schlaubischlump no, that is an oversight. Let me look into that.

**Comment by mrzapp** [comment]
@Schlaubischlump it seems to be because of the amount of extra fields in there, `P0Y0M0DT0H15M0S`. It's rather unusual to include years, months, and days in a cooking time definition. But we should make sure to properly ignore the extra fields.

The offending line is [here](https://github.com/mrzapp/nextcloud-cookbook/blob/master/lib/Service/RecipeService.php#L323)

Would you like to have a go at fixing it, since you have the test data? You can go ahread and remove the _test field while you're at it.

**Comment by Schlaubischlump** [comment]
Yes I take a look into it.

**Comment by Schlaubischlump** [comment]
What should we do with the year / month / day values ? Should we convert them to minutes or just ignore them ?

**Comment by mrzapp** [comment]
@Schlaubischlump I think we should ignore them. It's too much of a fringe case

**Comment by Schlaubischlump** [comment]
In this case
