### ISSUE TITLE
Update to 0.6 - Total Mess

### ISSUE THREAD

**Issue by hitam4450** [mrzapp/nextcloud-cookbook#166]
Hi, I just upgraded cookbook from 0.5.7 --> 0.6 and the upgrade is a total mess:

-- Pictures will be displayed on top of the page only - as a banner
-- No more categories available in the left pane - even though several categories are mentioned in ALL recipes
-- Start of cooking time display NEGATIVE value
-- Adding new recipe ---> still no category shown

-- stop testing !

best regards, hitam4450

NextCloud 18.0.3

**Comment by mrzapp** [comment]
1. Pictures are supposed to be displayed on top of the page, so what's the problem?
2. The categories in the left pane are based on actual categories now, instead of keywords
3. Can you paste the JSON of the recipe that this is happening on?
4. Same as 2
5. This app is not production ready, hence the `0` at the beginning of the version number. It's to be expected that we're testing and experimenting continuously.

**Comment by hitam4450** [comment]
Thank you very much for your feedback. I know the app isn't production ready yet.

Ok, I will check and  will get back to you !
Many thanks for your reply!

regards, hitam4450

**Comment by hitam4450** [comment]
Enclosed a screenshot of the current situation
![cookbook1](https://user-images.githubusercontent.com/9738727/77439625-8f767700-6de7-11ea-82b7-e8b231d81e6a.png)

**Comment by hitam4450** [comment]
Ok, I got oi with the question of categories....However I would rather prefer the keywords method !

regards, hitam4450

**Comment by hitam4450** [comment]
BTW, what is the use of the recipe URL for ???

**Comment by hitam4450** [comment]
Will it be possible to assign 2 or more categories to a recipe and then they show up in all categories assigned - instead of crating a new - combine category ??

regards, hitam4450

**Comment by hitam4450** [comment]
Many thanks for your effort and work to prepare the cookbook app, which will be used by many enthusiastic cooks around the world !

I'll be glad to help with testing, feedback and comments !

regards, hitam4450

**Comment by mrzapp** [comment]
@hitam4450 The recipe URL is just where you originally found it, but it's not relevant for your own recipes.  

You can only assign 1 category, but you can assign multiple keywords. Keywords are used only for search currently, but there may be a need to reintroduce keyword selection in some way.

@mcorteel any thoughts on a keyword selector in addition to the categories?

**Comment by hitam4450** [comment]
Besides Cooking time a filed of the temperature for the Oven might be necessary as well !

regards, hitam4450

**Comment by mcorteel** [comment]
@mrzapp My thought on keywords vs. categories is: why are there two distinct concepts when they seem to be used pretty much for the same thing?
Personnaly, I would get rid of categories in their current form, use keywords a categories and create a better interface (some kind of typeahead) to define those categories.

**Comment by hitam4450** [comment]
Keywords are sufficient & good enough for sorting and categorizing !

**Comment by mrzapp** [comment]
I don't think getting rid of categories is a way to go, we're trying to support the schema.org definition, and they implement both categories and keywords. They have separate uses.

Like, a category could be "breakfast", while a keyword could be "vegan". A dish is unlikely to be both breakfast and dinner, so that's a good use for a category, but it can easily be both vegan and indian, so that's a good use of keywords.

I think I'm going to close this issue, as it's getting a little weak in terms of focus. If we want a tag cloud or something like that, we'll create a bespoke issue
