### ISSUE TITLE
Change the names of the edit fields

### ISSUE THREAD

**Issue by GambaJo** [mrzapp/nextcloud-cookbook#182]
![31-03-_2020_09-33-54](https://user-images.githubusercontent.com/1378907/78009076-c517e480-7340-11ea-880f-e6954e3c50cf.jpg)
I'm using the KeePass Password Safe 2 and the Firefox AddOn Kee (https://www.kee.pm/). I think this AddOn identify the input fields by name and try to fill it with credentials.

When I want to edit an existing recipe, the AddOn replaces the name and the description of the recipe with credentials, because it thinks, this fields are for credentials.

I think, if the fields would have name/id, this problem will be solved.

**Comment by mrzapp** [comment]
@GambaJo they do have names:

![image](https://user-images.githubusercontent.com/2747428/78009189-ef69a200-7340-11ea-99f3-fa0ddb2d3068.png)

I think this issue lies with the Firefox addon being too optimistic about which fields to fill.

**Comment by GambaJo** [comment]
> 
> 
> @GambaJo they do have names:
> 
> ![image](https://user-images.githubusercontent.com/2747428/78009189-ef69a200-7340-11ea-99f3-fa0ddb2d3068.png)
> 
> I think this issue lies with the Firefox addon being too optimistic about which fields to fill.

This app is the only one with this problem, so I don't think, it's the AddOn. You can just rename this field in "title" for example.

**Comment by mrzapp** [comment]
The addon is looking for any input field with the attribute `[name="name"]`. It should at least be `username` or check if there is a `[type="password"]` field on the same page, which there isn't in this case, so it makes no sense to fill in user credentials. Also, why is it doing it automatically, without any action taken by the user? It smells like a lot of bad practices all around.

You may only see this issue in the Cookbook app currently, but the fault lies with KeePass regardless. Imagine if we accommodated every other poorly coded browser plugin, the work would never end :sweat_smile: 

I don't mean to be rude, but this is not our problem.

**Comment by GambaJo** [comment]
The AddOn works fine for me on every other site/app. I want it to fill the credantial fields automatically, so I don't have to do it manually. I think most of the login sites name their name field "name".
Yes, it's not your problem, it's mine, because the developer of the AddOn will say "Just change the name of the field". The usually fault ping pong between open source projects.

**Comment by mrzapp** [comment]
@GambaJo for this to fail on other sites, only 2 criteria need to be met:

1. You have a login for the site
2. An input field named "name" appears on a page other than the login form

If you want this problem to be solved, please create an issue with the add-on project. You're barking up the wrong tree.

**Comment by mcorteel** [comment]
@GambaJo This is far from the only issue of this kind with the Kee addon (https://github.com/kee-org/browser-addon/issues).

The developper (@luckyrat according to github) will not say "Just change the name of the field", because it wouldn't make any sense and @mrzapp's answer seems like a sensible fix. Please correct me if I'm wrong @luckyrat.

But the truth is that he might not fix this problem right away. Don't pin this on open source projects, because a closed source project refusing to fix an issue leaves no alternative, while an open source project gives anyone the possibility to fix it themselves or have someone fix it for them.

Anyway, like @mrzapp said, you're barking up the wrong tree and you really should open an issue with the Kee project!

**Comment by luckyrat** [comment]
The short answer is to disable automatic form filling for this KeePass entry. There are more advanced approaches if the quick fix is undesirable (e.g. set a more specific web page for the sign-in form, alter the default white-listed form field names for just this website, make sure the KeePass entry has an accurate record of the desired sign-in form fields, etc.). If you need details on any of this please look on the Kee support forum at https://forum.kee.pm rather than add additional discussion to this project's issue tracker.

No heuristic for determining which form fields relate to a particular KeePass entry can be perfect, hence the availability of many ways to work around the quirks of specific websites - sometimes the responsibility for resolution firmly sits on their shoulders but in a case like this, the suggested change of a form field name to "title" could only temporarily resolve the issue. It would break again if that becomes a common name within sign-in form fields and Kee has to start filling it, or if some other user with some other password manager comes along and claims the solution to their problem is to switch it back to "name". So, although I take issue with @mrzapp's implication that only poorly coded browser extensions will behave in this way, the overall point is valid - the work to accommodate every extension would never end.

Kee's heuristic is far more involved than just looking for any field on a form with a name "name"; this is in an attempt to handle the many millions of differently behaved websites in the wild (for example, you must have come across a sign-in form where there is no password field visible until *after* the username/email/name/id/etc. has been submitted). It's something I'll keep improving but it's definitely not trivial and is never-ending so there is no guarantee when I'll next have time to review the heuristics, nor that any change will alter the default behaviour on this specific website.

**Comment by mrzapp** [comment]
Sorry about that comment @luckyrat, it was uncalled for. I do respect your project, and I honestly had no idea what I was talking about.

We're all just trying our best, and I'm dead certain you will find stupid code in all of my projects anyway, so it's not like I'm above my own criticism.

Good luck with your project, and thank you for donating your time to develop it.
