### ISSUE TITLE
internal server error when not logged in

### ISSUE THREAD

**Issue by RobRobM** [mrzapp/nextcloud-cookbook#204]
When I go to nextcloud_instance/apps/cookbook when I am not logged in I get the error:

"Interne serverfout
De server was niet in staat je aanvraag te verwerken."

Rough translation:

"Internal server error
The server was unable to process your request."

I mostly get this error when I leave a browser tab open on a recipe as quit Firefox. When restarting Firefox later the tabs try to reload and the recipe fails to load when I am logged out due to time and inactivity.

Love the cookbook by the way

**Comment by Schlaubischlump** [comment]
Isn‘t this expected behavior? I mean you are not logged in, nobody should be able to access your data without being loggend in

**Comment by RobRobM** [comment]
Sorry I"ll  clarify. When accessing other apps like files, activity, deck you can login and get directed to the app.
https://nextcloud/login?redirect_url=/apps/deck/

**Comment by RobRobM** [comment]
When not logged in and going to:
https://nextcloud/apps/deck/
Becomes
https://nextcloud/login?redirect_url=/apps/deck/

**Comment by mcorteel** [comment]
@mrzapp This issue stems from the constructor or `RecipeService`. All arguments are required, but when the user is not logged in, `$UserId` is `null` when it expects a `string`.
So the fix is just to replace the type hint by `?string $UserId` :slightly_smiling_face: 
I'm not sure where to push this. Is master still the development branch?

**Comment by mrzapp** [comment]
@mcorteel please push to master, yes :)
