### ISSUE TITLE
Import several steps/ingredients at once

### ISSUE THREAD

**Issue by Christoph-Wagner** [mrzapp/nextcloud-cookbook#265]
**Is your feature request related to a problem? Please describe.**
When there is no marked-up recipe to import, for example when it’s a reddit post, to manually create a recipe, I need to paste one line, press enter, and repeat that step many times

**Describe the solution you'd like**
My current recipe manager is copymethat.com, to enter ingredients, it’s a big textfeld and it converts every line to one ingredient (for steps every paragraph to one step). That way I copy/paste 2 things and got all the steps and ingredients done. 

**Willingness to work on this**
If the maintainers think this sounds like a good idea, I’d be willing to look into implementing this myself. I haven’t worked with PHP in years, but this does not sound like something needing deep knowledge of it. *edit: and I just checked the source, Vue on the other hand is something I work with regularly :)* 

I can see two ways to do this:

1. Have a "Bulk Add" step/ingredient/tools button that adds a textarea for pasting
2. Do away with the current flow and just have textareas. It seems like a better solution to me, but maybe I’m missing something why people would prefer the current flow of getting a new distinct line on enter/pressing add.

**Comment by mrzapp** [comment]
@Christoph-Wagner the reason for the current flow is the format of https://schema.org/Recipe, which is the gold standard for how recipe data should be stored. It's not within the scope of this app to work with non-standard recipe formats, like multi line text strings.

Since your case is a bit of a niche, I'd recommend you create your own automation tool that parses the format you're working with into a recipe.json file, put that inside a named folder in your recipes directory and then rescan the library. That way you can have your cake and eat it too :)

If it was me, I'd just split the string by every newline and assign the resulting array to the "recipeInstructions" field.
