### ISSUE TITLE
Cookbook updates should trigger file revision creation

### ISSUE THREAD

**Issue by Luticus** [mrzapp/nextcloud-cookbook#33]
So what I'm trying to do is combine your cookbook app with the group folders app to create a central cookbook that everyone on the nextcloud server can contribute to.  Unfortunately if I give everyone write but deny delete there's still the possibility of vandalizing or accidentally messing up a recipe.  What would mitigate this is if the file revisions were triggered when changes were made to the cookbook entry through the app.  This doesn't seem to be the case right now as I made a change, adding a new instruction to an entry and then went and inspected the .json file for it and observed that it had no revision history, even though a change was made.

**Comment by mrzapp** [comment]
Sounds like a good addition, the documentation for writing files is [here](https://docs.nextcloud.com/server/16/developer_manual/app/storage/filesystem.html#writing-to-a-file), you may be able to find something useful.

**Comment by mrzapp** [comment]
@Luticus I can't find anything on the topic here: https://docs.nextcloud.com/server/latest/developer_manual/search.html?q=revision&check_keywords=yes&area=default

Are you aware of any other words that describe this feature?

**Comment by Luticus** [comment]
Maybe try:  https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/versions.html?highlight=files%20versions

I'm definitely not a Nextcloud app developer but that's my best guess.

**Comment by Teifun2** [comment]
Is it possible to edit an entry instead of deleting and adding it when they get updated?

[Currently](https://github.com/mrzapp/nextcloud-cookbook/blob/6d01b95b680b9e7ec64141d858ba2e5087307e4d/lib/Controller/RecipeController.php#L122) when a entry is updated the file gets deleted and written. I'm not surprised that nextcloud cannot keep revisions of such behavior.

**Comment by mrzapp** [comment]
@Teifun2 Aha, you've got a point. The change would be in the `lib/Service/RecipeService::updateRecipe` method

**Comment by Teifun2** [comment]
I looked into it a little further and i noticed that the RecipeService::addRecipe already has the capabilities to deal with an "existing" Recipe. 

To me it seems we could just [remove the delete statement](https://github.com/mrzapp/nextcloud-cookbook/blob/6d01b95b680b9e7ec64141d858ba2e5087307e4d/lib/Controller/RecipeController.php#L122) and the files should be updated instead of replaced. 
I tried it on my local instance and it worked but my testing was rather minor. The File had a revision and there was no duplication just by removing the line with ` $this->service->deleteRecipe($id);`.

It would be greate if somone else could test that, because i'm unsure if i understand all the implications that might have. @mrzapp

**Comment by mrzapp** [comment]
@Teifun2 that's our culprit! The reason for that delete statement was so we could clear the image cache, which no longer works as it used to, so the delete statement is redundant.

Feel free to make the change and merge it into `develop`. I will test all issues afterwards and push a new release.
