### ISSUE TITLE
Use appdata-folder for cache

### ISSUE THREAD

**Issue by haeckle** [mrzapp/nextcloud-cookbook#63]
First: thanks for the great app!

Currently the cache is saved in a separate folder in the root directory of the nextcloud data directory.
However their is a special "appdata_<hash>" directory which can be used for such things ([Explanation](https://help.nextcloud.com/t/what-is-the-appdata-ocpom4nckwru-directory/19900)).
API-Documentation is available: https://docs.nextcloud.com/server/stable/developer_manual//api/OC/Cache/index.html
Example can be found in the bookmarks app: https://github.com/nextcloud/bookmarks/blob/master/lib/FileCache.php

**Comment by mrzapp** [comment]
@haeckle Thanks for pointing that out. 

As @brogers-navex and i discussed in [this](https://github.com/mrzapp/nextcloud-cookbook/pull/58) pull request, and as has been requested [here](https://github.com/mrzapp/nextcloud-cookbook/issues/62), we will be moving away from caching all together, as storing the images locally as an explicit feature turns out to be more flexible in the long run.

I will close this issue, as a different solution will be implemented.
