### ISSUE TITLE
references to nonexistent master branch

### ISSUE THREAD

**Issue by geeseven** [mrzapp/nextcloud-cookbook#75]
Greetings,

Currently, there are some dead links in the main and translationfiles README.md files that refer to a nonexistent master branch.  A search shows there are [more references to a master branch][0].  I was about to submit a pull request with a simple `s/master/develop`, but unsure which branch is needed for the automation scripts.  

[0]: https://github.com/mrzapp/nextcloud-cookbook/search?q=master&type=Code

**Comment by christianlupus** [comment]
This is due to the fact that recently the master branch was renamed to develop and a new stable branch was created to simplify collaboration.

A plain regex based replacement will not suffice. E.g. the file `.travis.yml` links to the PostgreSQL version to be used for testing. Although testing is not implemented yet, I did not check every other occurence of the term `master`.

**Comment by geeseven** [comment]
Thanks for the timely update and confirming my concerns about a blanket change. You were also quick to submit a pull request, nice.
