### ISSUE TITLE
Recipe sharing

### ISSUE THREAD

**Issue by quamok** [mrzapp/nextcloud-cookbook#82]
Hello there, thank you for this great app. I have a feature suggestion: be able to share recipes with another NC user.

I'd like to be able to share the recipes with my gf without giving her full access to my NC data.

I'm quite new to NC so I'm not sure if this is even possible.

Thanks again for developing this!

**Comment by theonlytruth** [comment]
Hey quamok,
I didn't try for myself, but if you want to share your whole recipe folder, you should be able to give your girlfriend access to the recipe folder in your NC. Like a normal file sharing. Then she only has to choose this folder in the cookbook app as recipe folder.

**Comment by christianlupus** [comment]
See e.g. [this issue](https://github.com/mrzapp/nextcloud-cookbook/issues/19#issuecomment-517121374). There is a way described how one can share a set of recipes between multiple users.

I will close this issue here as I think it is resolved. If you have more questions, please simply post them, I will reopen if need arises.

Thanks for reporting!

**Comment by quamok** [comment]
Thank you I found a new tab on Github for closed issues. I'm not used to the platform :)
I got it working!
