### ISSUE TITLE
Incorrect Servings

### ISSUE THREAD

**Issue by paulcalabro** [mrzapp/nextcloud-cookbook#96]
I tried importing:

https://pinchofyum.com/spicy-shrimp-tacos-with-garlic-cilantro-lime-slaw

It's interpreting **Yield: 4 (2 small tacos each)** as **Servings: 42**.
I'm guessing this is a regex issue. What's the best way to debug this issue?

**Comment by mrzapp** [comment]
@paulcalabro My suggestion would be to change [this](https://github.com/mrzapp/nextcloud-cookbook/blob/develop/lib/Service/RecipeService.php#L150) so that it makes use of regex to find the first uninterrupted string of numbers and parse it to an integer.

Would you be able to contribute this change, or should we handle it?

**Comment by paulcalabro** [comment]
@mrzapp I can make that change. I'll take care of that a little bit later.
